### ISSUE TITLE
Locale decimal separator issue

### ISSUE THREAD

**Issue by maincoon** [memtrip/eosreach-android#4]
Decimal separator for russian (and not only) locale is "," not "." this leads to "invalid asset format" error due to incorrect formatted EOS amount.

![image](https://user-images.githubusercontent.com/6287984/53014032-458ac700-3458-11e9-912a-6262aa12a231.png)
![image 1](https://user-images.githubusercontent.com/6287984/53014042-4d4a6b80-3458-11e9-8308-57442946748b.png)
![image 2](https://user-images.githubusercontent.com/6287984/53014044-4facc580-3458-11e9-8748-26beef49d210.png)

**Comment by samkirton** [comment]
This is fixed on the latest master branch, and an update has been pushed to Google Play.
